version: '3.8'
services: 
    api:
        container_name: api
        restart: on-failure
        build: ./
        volumes: 
            - ./:/usr/src/api/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
            FLASK_ENV: development

    redis:
        image: "redis:alpine"
        ports: 
            - 6379:6379
